spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.177.131:8848
    alicloud:
      access-key: LTAI5tD5QrQopZcDJvTNTmh9
      secret-key: IxpQ8JHFJ46njIs8Q3XooP2pR2w7Z6
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: ccc-gulimall
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: 908e94ccf08b4476ba6c876d13f084ad
        appcode: 79c84959aa294eb886b588b8f825c4c9





  application:
    name: gulimall-third-party


server:
  port: 30000